FROM maven:3.9.6-eclipse-temurin-21 AS build

WORKDIR /app

COPY . .

RUN mvn -pl analytics-service clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY analytics-service/target/*.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]